#pragma once

#define MACRO_USE_SUPERSAMPLE_TEST false
#define MACRO_USE_SUPERSAMPLE (MACRO_USE_SUPERSAMPLE_TEST || true)
#define MACRO_SUPERSAMPLE_SCALE 3

#define MACRO_NUM_THREADS 12

//MUST BE A PERFECT SQUARE
#define MACRO_NUM_LIGHT_SAMPLES 12

#define MACRO_STARFIELD_BACKGROUND_ON false
#define MACRO_RENDER_BOUNDING_BOX false
#define MACRO_REFLECTION_ON true
#define MACRO_REFRACTION_ON false

#define PI 3.1415926535897932384
